<a href="https://colab.research.google.com/github/leaping96/Ajou_DataMining/blob/main/projectCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#드라이브에 접근할 수 있도록 아래 코드 입력
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#불러올 파일의 경로를 filename 변수에 저장
filename = '/content/drive/Shareddrives/데마/dataset.csv'

In [ ]:
import pandas as pd
import numpy as np
#pandas read_csv로 불러오기
data = pd.read_csv(filename)
data.head()

세분화링크ID  위험도  위험등급   시도  ... 부상신고자수 도로위험도Basic 하늘상태  돌발상황
0  2520003300_42150350_1  0.0     1  강원도  ...      0        0.0   맑음      
1  2520003300_42150350_2  0.0     1  강원도  ...      0        0.0   맑음      
2  2520003400_42150350_1  0.0     1  강원도  ...      0        0.0   맑음      
3  2520003400_42150350_2  0.0     1  강원도  ...      0        0.0   맑음      
4  2520004500_42150350_1  0.0     1  강원도  ...      0        0.0   맑음      

[5 rows x 17 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# 1. 불러온 데이터를 정규화/표준화 등 전처리가 필요한 부분 (동현)

train_sample = data.loc[:,['도로길이_m','차로수_편도', '사고건수', '사망자수', '중상자수', '경상자수'] ]
target = data.loc[:,['도로위험도Basic'] ]

train_sample.head()













도로길이_m  차로수_편도  사고건수  사망자수  중상자수  경상자수
0   30.000100       2     0     0     0     0
1  277.308438       2     0     0     0     0
2   30.000100       2     0     0     0     0
3  268.946612       2     0     0     0     0
4  200.000100       2     0     0     0     0

In [ ]:
import missingno as msno 
# missingno 패키지 import (결측값 확인)

train_sample.isnull().sum() #결측 data값 존재 x

도로길이_m    0
차로수_편도    0
사고건수      0
사망자수      0
중상자수      0
경상자수      0
dtype: int64

In [ ]:
#1 standardScaler code
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(train_sample, target, test_size=0.33, random_state = 85)

scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)
print('스케일 조정 전 features Min value : \n',format(X_train.min(axis=0))) 
print('스케일 조정 전 features Max value : \n',format(X_train.max(axis=0)))
print('스케일 조정 후 features Min value : \n',format(X_train_scale.min(axis=0)))
print('스케일 조정 후 features Max value : \n',format(X_train_scale.max(axis=0)))

스케일 조정 전 features Min value : 
 도로길이_m    30.0001
차로수_편도     1.0000
사고건수       0.0000
사망자수       0.0000
중상자수       0.0000
경상자수       0.0000
dtype: float64
스케일 조정 전 features Max value : 
 도로길이_m    322.207954
차로수_편도      8.000000
사고건수       39.000000
사망자수        2.000000
중상자수       16.000000
경상자수       54.000000
dtype: float64
스케일 조정 후 features Min value : 
 [-1.31426552 -1.09029412 -0.45839254 -0.11467328 -0.33619517 -0.39402162]
스케일 조정 후 features Max value : 
 [ 2.52620372  5.28159139 20.23487415 16.90107661 21.19145558 19.82950933]


In [ ]:
#2 RobustScaler code
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(train_sample, target, test_size=0.33, random_state = 85)
scaler = RobustScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

print('스케일 조정 전 features Min value : \n',format(X_train.min(axis=0))) 
print('스케일 조정 전 features Max value : \n',format(X_train.max(axis=0)))
print('스케일 조정 후 features Min value : \n',format(X_train_scale.min(axis=0)))
print('스케일 조정 후 features Max value : \n',format(X_train_scale.max(axis=0)))

스케일 조정 전 features Min value : 
 도로길이_m    30.0001
차로수_편도     1.0000
사고건수       0.0000
사망자수       0.0000
중상자수       0.0000
경상자수       0.0000
dtype: float64
스케일 조정 전 features Max value : 
 도로길이_m    322.207954
차로수_편도      8.000000
사고건수       39.000000
사망자수        2.000000
중상자수       16.000000
경상자수       54.000000
dtype: float64
스케일 조정 후 features Min value : 
 [-0.55282292 -0.5         0.          0.          0.          0.        ]
스케일 조정 후 features Max value : 
 [ 1.22616917  3.         39.          2.         16.         54.        ]


In [ ]:
# 3 Normalizer code
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(train_sample, target, test_size=0.33, random_state = 85)
scaler = Normalizer()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)
print('스케일 조정 전 features Min value : \n',format(X_train.min(axis=0))) 
print('스케일 조정 전 features Max value : \n',format(X_train.max(axis=0)))
print('스케일 조정 후 features Min value : \n',format(X_train_scale.min(axis=0)))
print('스케일 조정 후 features Max value : \n',format(X_train_scale.max(axis=0)))

스케일 조정 전 features Min value : 
 도로길이_m    30.0001
차로수_편도     1.0000
사고건수       0.0000
사망자수       0.0000
중상자수       0.0000
경상자수       0.0000
dtype: float64
스케일 조정 전 features Max value : 
 도로길이_m    322.207954
차로수_편도      8.000000
사고건수       39.000000
사망자수        2.000000
중상자수       16.000000
경상자수       54.000000
dtype: float64
스케일 조정 후 features Min value : 
 [0.60946035 0.00310357 0.         0.         0.         0.        ]
스케일 조정 후 features Max value : 
 [0.99999518 0.25766185 0.39974949 0.03324101 0.21633334 0.71103471]


In [ ]:
#2-1. poly 커널을 통하여 예측하기 (창희)
import sys
np.set_printoptions(threshold=sys.maxsize)

# Generate sample data
# 300개 / 100개로 1차 train 후  => 3000개 / 200개+@로 2차train 할것!
X = X_train_scale[0:3000]
y = Y_train[0:3000]

y = np.array(y, dtype=np.float64).ravel()
svr = SVR(kernel = 'poly', gamma='auto', degree=2, epsilon=0.1).fit(X, y)

X_test_scale = X_test_scale[0:300]
Y_test = Y_test[0:300]

# 예측score(정확도) 계산하여 출력하기
score = svr.score(X_test_scale,Y_test)
print(score)


In [ ]:
#3-1 예측한 데이터 바탕으로 후처리가 들어가야 할 부분 (용민)

In [ ]:
# 예측score(정확도) 계산하여 출력하기
score = svr.score(x_test,y_test_)
score

In [ ]:
#2-2 linear 커널을 통하여 예측하기(정우)
import sys
np.set_printoptions(threshold=sys.maxsize)

# Generate sample data
X = X_train_scale
y = Y_train
y = np.array(y, dtype=np.float64).ravel()

param_grid = [
    {'kernel': ['linear'],'C':[0.001,0.01,0.1,1,10,100]}
]
svm_reg = SVR()

svr = SVR(kernel = 'linear', C = '10').fit(X, y)

score = svr.score(X_test_scale, Y_test)
print(score)

In [ ]:
#3-2 예측한 데이터 바탕으로 후처리가 들어가야 할 부분(용민)

In [ ]:
# 예측score(정확도) 계산하여 출력하기
score = svr.score(x_test,y_test_)
score

NameError: ignored